# Generated by Django 5.1.4 on 2025-01-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients_list', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('cocktail', 'Cocktail'), ('beer', 'Beer'), ('wine', 'Wine'), ('non_alcoholic', 'Non-Alcoholic'), ('soft_drink', 'Soft Drink')], default='Soft Drink', max_length=100)),
                ('is_alcoholic', models.BooleanField(default=True)),
                ('serving_size', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
    ]
